from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import Protocol

from .models import (
    Anime,
    AniListCandidate,
    AppSettings,
    ArchiveRecord,
    ArchivedAnime,
    EpisodeSchedule,
    FollowRecord,
    FollowedAnime,
    PlaybackLink,
    Season,
)


class CatalogProvider(Protocol):
    def list_season(self, year: int, season: Season) -> list[Anime]: ...

    def search(self, query: str) -> list[Anime]: ...


class ScheduleProvider(Protocol):
    def find_candidates(self, anime: Anime) -> list[AniListCandidate]: ...

    def get_schedule(self, anime_id: str, anilist_id: int) -> list[EpisodeSchedule]: ...


class Repository(Protocol):
    database_path: Path

    def initialize(self) -> None: ...

    def upsert_anime(self, anime: Anime | Iterable[Anime]) -> None: ...

    def get_anime(self, anime_id: str) -> Anime | None: ...

    def find_anime_by_external(self, bgm_id: int | None, anilist_id: int | None) -> Anime | None: ...

    def get_season(self, year: int, season: Season) -> list[Anime]: ...

    def get_following(self) -> list[FollowedAnime]: ...

    def follow_anime(self, anime_id: str) -> None: ...

    def save_follow_record(self, record: FollowRecord) -> None: ...

    def update_follow(self, anime_id: str, **changes: object) -> None: ...

    def unfollow_anime(self, anime_id: str) -> None: ...

    def replace_schedules(self, anime_id: str, schedules: Iterable[EpisodeSchedule]) -> None: ...

    def save_playback_link(self, link: PlaybackLink) -> None: ...

    def delete_playback_link(self, link_id: str) -> None: ...

    def get_archive(self) -> list[ArchivedAnime]: ...

    def archive_anime(self, record: ArchiveRecord) -> None: ...

    def restore_from_archive(self, anime_id: str) -> None: ...

    def delete_archive(self, anime_id: str) -> None: ...

    def get_settings(self) -> AppSettings: ...

    def save_settings(self, settings: AppSettings) -> None: ...

    def create_database_snapshot(self, path: Path) -> None: ...

    def restore_database_snapshot(self, path: Path) -> None: ...
